version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.20
    container_name: mysql
    volumes:
      - ./datadir:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root123456"
      - "MYSQL_DATABASE=wvp"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes
  wvp:
    build:
      context: ./wvp
      args:
        gitUrl: "https://gitee.com/pan648540858"
        zlmGitUrl: "https://gitee.com/xia-chu/ZLMediaKit"
    restart: always
    ports:
      - "5060:5060"
      - "5060:5060/udp"
      - "18080:18080"
      - "80:80"
      - "11000:10000/tcp"
      - "11000:10000/udp"
      - "40000-40500:30000-30500/tcp"
      - "40000-40500:30000-30500/udp"
    volumes:
      - ./video:/opt/media/www/record/
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
      - ./zlm/config.ini:/opt/media/config.ini
      - ./zlm/snap/:/opt/media/www/snap/
      - ./wvp/application.yml:/opt/wvp/config/application.yml
    environment:
      TZ: "Asia/Shanghai"
      # [必须修改] 本机的IP
      WVP_HOST: 192.168.50.50
      WVP_PWD: aseqw_+hiy123
      WVP_DOMAIN: 6101130049
      WVP_ID: 61011300490000000001
      ZLM_HOST: 192.168.50.50
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: root
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG: --media.id=AIi7b9Hyz3i925jg --media.ip=192.168.50.50 --spring.datasource.password=root123456 --spring.datasource.url=jdbc:mysql://192.168.50.50:3306/wvp?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - redis
